### ISSUE TITLE
Installed, but how do I access the REST endpoint?

### ISSUE THREAD

**Issue by inturbidus** [rcorral/com_api#1]
I have installed the component successfully.  Now, how do I access the REST endpoint?  Also, what is the domain for in the configuration of an API Key?

**Comment by rcorral** [comment]
I added another repo with all of the plugins that I have built, you can see that here: https://github.com/rcorral/com_api-plugins

Once you install one of the plugins, for example the users plugin, you would do a call like this:
index.php?option=com_api&token=xxxxx&app=users&resource=user
depending on the type of your request a different part of that resource would be executed.

For the domain, it is not required from what I remember, but it would be the domain from the server or host that is accessing the API.

I had previously renamed the component to a different name as the original extension was written by Brian: https://github.com/brianedgerton/com_api but it doesn't look like he is keeping up with it as I submitted a pull request a year ago to make it 2.5 compatible but he never accepted it.

Let me know if you run into any other problems, like I said I renamed it twice so I might've missed something, mostly on the plugins repo.

**Comment by rcorral** [comment]
I just noticed that I told you that you pass the API key as the "token" parameter, but the parameter name is supposed to be "key".
