### ISSUE TITLE
Joomla 2.5 + rest api

### ISSUE THREAD

**Issue by ghost** [rcorral/com_api#2]
Hi I installed the Joomla rest api ( rcorral-com_api-plugins-1dc4e5a ) with ./scripts/symlink.sh, it created an link from joomla root dir to api dir.

But now what would be the next step, what plugin need to install & from where and how to test the rest api.

can I know this in details.

Thanks

**Comment by rcorral** [comment]
If you want to simply get up and running, I suggest that you build the component, using the build script from the [com_api-plugins](https://github.com/rcorral/com_api-plugins) repo as it will build the component and the plugins into one installable package.

If you want to symlink, then you really only need to use the symlink script fro this repo, and build plugins that you want by following the examples from the com_api-plugins repo, unless there are any plugins that you will actually use from the other repo then you really don't need to symlink the plugins.

**Comment by ghost** [comment]
Thanks rcorral for your quick response.

I am able to install plugin & component successfully.

I tried access this with Rest API client at chrome browser as 

http://xxxxxx/demoapi/index.php?option=com_api&key=bb2333ca989f4ce0a0881097b44f720f1af6e951&app=users&resource=userslist

getting the response code 200, but not any data and showing error as 

Unable to parse JSON response.  dismiss

Can you help in this.

Thanks

**Comment by rcorral** [comment]
Could you send me the exact response from a curl -v request to that URL?

**Comment by ghost** [comment]
Hi rcorral thanks for your reply.

Actually I am not getting any response, but in chrome console following error shows:

Failed to load resource chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/img/help-hint.png
(-:-) 2012-10-15 21:04:23,983 [ERROR] Application error
com.google.gwt.event.shared.UmbrellaException: One or more exceptions caught, see full set in UmbrellaException#getCauses
    at Unknown.Bc(Unknown Source)
    at Unknown.$c(Unknown Source)
    at Unknown.ls(Unknown Source)
    at Unknown.ns(Unknown Source)
    at Unknown.wr(Unknown Source)
    at Unknown.Vqb(Unknown Source)
    at Unknown.nrb(Unknown Source)
Caused by: com.google.gwt.json.client.JSONException: Error parsing JSON: SyntaxError: Unexpected token <
    at Unknown.Bc(Unknown Source)
    at Unknown.Xc(Unknown Source)
    at Unknown.Zc(Unknown Source)
    at Unknown.gx(Unknown Source)
    at Unknown.ky(Unknown Source)
    at Unknown.iy(Unknown Source)
    at Unknown.jy(Unknown Source)
 C1B335B02428A3779D52F9EE82F32238.cache.html:3298
(-:-) 2012-10-15 21:04:34,171 [ERROR] Application error
com.google.gwt.event.shared.UmbrellaException: One or more exceptions caught, see full set in UmbrellaException#getCauses
    at Unknown.Bc(Unknown Source)
    at Unknown.$c(Unknown Source)
    at Unknown.ls(Unknown Source)
    at Unknown.ns(Unknown Source)
    at Unknown.wr(Unknown Source)
    at Unknown.Vqb(Unknown Source)
    at Unknown.nrb(Unknown Source)

**Comment by rcorral** [comment]
Unfortunately that doesn't tell me much, if you could do a CURL or send me the response body and response headers then we could go from there.

**Comment by ghost** [comment]
I made following curl request at terminal

curl -i H "Accept: application/json" http://xxxxx/demoapi/index.php?option=com_api&key=bb2333ca989f4ce0a0881097b44f720f1af6e951&app=users&resource=userslist

also 

curl --request GET http://xxxxx/demoapi/index.php?option=com_api&key=bb2333ca989f4ce0a0881097b44f720f1af6e951&app=users&resource=userslist

through terminal and got following output 

[1] 3204
[2] 3205
[3] 3206
[demo@localhost ~]$ curl: (6) Could not resolve host: H; Cannot allocate memory
curl: (6) Could not resolve host: Accept: application; Cannot allocate memory
HTTP/1.1 400 Bad Request
Date: Tue, 16 Oct 2012 03:18:00 GMT
Server: Apache/2.2.16 (Fedora)
X-Powered-By: PHP/5.3.8
Set-Cookie: c03523fc15e3afba0d6527a27d90e6d5=ndo3pr42bmtj4vpip6e52b8ii4; path=/
Status: 400
Cache-Control: no-cache
Pragma: no-cache
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
.
.
.
. and 
 --- complete front page in html format (Tool length html so not adding )

**Comment by rcorral** [comment]
This is odd, it looks like it is going into the API component by the Content-Type header response. But it seems like somewhere inside the component it is having a problem.

Have you tried saving the configuration of the component?
