### ISSUE TITLE
Users plugin

### ISSUE THREAD

**Issue by ghost** [rcorral/com_api#3]
Hi

I am manually compressing the user plugin under  "rcorral-com_api-plugins-1dc4e5a/code/plugins/api"

as  "users.zip"   and when trying to install it through standard joomla extension manager, getting following error

JInstaller: :Install: File does not exist /var/www/html/demoapi/tmp/install_507c1c7e7f51c/users/language/en-GB/en-GB.plg_api_users.ini

Any help..

**Comment by rcorral** [comment]
That is because you also need to grab the language files on the /administrator/ folder and place them in the correct spot to package up the plugin.

I am also closing this issue, as it is not related to com_api, post this on com_api-plugins.
